services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Mount your local SQL file into the initialization folder
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql:ro

volumes:
  db_data: